name: frobitz-app
recipe: wordpress
config:
  php: '8.0'
  composer_version: '2.4.1'
  via: apache
  webroot: app
  database: mysql
  xdebug: true
tooling:
  wp:
    service: appserver
services:
  appserver:
    run: 
      - scripts/build.sh
